///////////////////////////////////////////////////////////
//  AbstractBaseController.cs
//  Implementation of the Class AbstractBaseController
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:39:38
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class AbstractBaseController {

	private DaoInterface dataBaseService;
	public DaoInterface m_DaoInterface;

	public AbstractBaseController(){

	}

	~AbstractBaseController(){

	}

	public HttpResponse processRequest(){

		return null;
	}

}//end AbstractBaseController