///////////////////////////////////////////////////////////
//  Characteristic.cs
//  Implementation of the Class Characteristic
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:40:47
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Characteristic : Mechanicalkeyboard {

	public String cable_type;
	public String color;
	public int id;
	public String key_type;
	public int price;
	public String switch_type;

	public Characteristic(){

	}

	~Characteristic(){

	}

}//end Characteristic