///////////////////////////////////////////////////////////
//  DaoInterface.cs
//  Implementation of the Interface DaoInterface
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:39:15
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface DaoInterface  {

	/// 
	/// <param name="entity"></param>
	void add(Entity entity);

	/// 
	/// <param name="id"></param>
	void delete(int id);

	/// 
	/// <param name="id"></param>
	void getById(int id);

	void update();
}//end DaoInterface