///////////////////////////////////////////////////////////
//  DataBaseController.cs
//  Implementation of the Class DataBaseController
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:39:03
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DataBaseController : DaoInterface {

	private String connectionPassword;
	private String connectionURL;
	private String connectionUser;

	public DataBaseController(){

	}

	~DataBaseController(){

	}

	/// 
	/// <param name="entity"></param>
	public void add(Entity entity){

	}

	/// 
	/// <param name="id"></param>
	public void delete(int id){

	}

	/// 
	/// <param name="id"></param>
	public void getById(int id){

	}

	public void update(){

	}

}//end DataBaseController