///////////////////////////////////////////////////////////
//  DeliveryController.cs
//  Implementation of the Class DeliveryController
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:40:29
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DeliveryController : AbstractBaseController {

	public DeliveryController(){

	}

	~DeliveryController(){

	}

	/// 
	/// <param name="user"></param>
	private int changeStatusOfOrder(Users user){

		return 0;
	}

	/// 
	/// <param name="user"></param>
	private void getStatusOfOrder(Users user){

	}

	private void logout(){

	}

	public override HttpResponse processRequest(){

		return null;
	}

}//end DeliveryController