///////////////////////////////////////////////////////////
//  DirectorController.cs
//  Implementation of the Class DirectorController
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:40:38
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DirectorController : AbstractBaseController {

	private PaymentSystemController paymentSystemController;
	private PrinterController printerController;
	public PrinterController m_PrinterController;

	public DirectorController(){

	}

	~DirectorController(){

	}

	private Report getReport(){

		return null;
	}

	private void logout(){

	}

	public override HttpResponse processRequest(){

		return null;
	}

}//end DirectorController