///////////////////////////////////////////////////////////
//  Entity.cs
//  Implementation of the Class Entity
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:39:25
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Entity {

	public int id;

	public Entity(){

	}

	~Entity(){

	}

}//end Entity