///////////////////////////////////////////////////////////
//  GuestController.cs
//  Implementation of the Class GuestController
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:39:31
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class GuestController : AbstractBaseController {

	public GuestController(){

	}

	~GuestController(){

	}

	/// 
	/// <param name="keyboard"></param>
	private void addToCart(Mechanicalkeyboard keyboard){

	}

	/// 
	/// <param name="filter"></param>
	private List<Keyboard> findFilteredKeyboards(String filter){

		return null;
	}

	/// 
	/// <param name="id"></param>
	private KeyboardEntity getCharacteristics(int id){

		return null;
	}

	private void login(){

	}

	public override HttpResponse processRequest(){

		return null;
	}

	private void register(){

	}

}//end GuestController