///////////////////////////////////////////////////////////
//  ManagerController.cs
//  Implementation of the Class ManagerController
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:40:18
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ManagerController : AbstractBaseController {

	public class PaymentController {

		public PaymentController(){

		}

		~PaymentController(){

		}

		public void GetPaymentReport(){

		}

	}//end PaymentController

	private Storage storage;
	public ProducerController m_ProducerController;
	public ProviderController m_ProviderController;

	public ManagerController(){

	}

	~ManagerController(){

	}

	/// 
	/// <param name="lens"></param>
	private void addToStorage(Mechanicalkeyboard lens){

	}

	/// 
	/// <param name="id"></param>
	private void deleteFromStorage(int id){

	}

	/// 
	/// <param name="order"></param>
	private void editOrder(Orders order){

	}

	/// 
	/// <param name="user"></param>
	private void editStatusOfOrder(Users user){

	}

	private List<Keyboard> getList(){

		return null;
	}

	private void logout(){

	}

	public HttpResponse processRequest(){

		return null;
	}

	private void terminateSystem(){

	}

	private void termonateSystem(){

	}

}//end ManagerController