///////////////////////////////////////////////////////////
//  Mechanicalkeyboard.cs
//  Implementation of the Class Mechanicalkeyboard
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:41:10
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Mechanicalkeyboard : Entity {

	public String cable_type;
	public String color;
	public int id;
	public String key_type;
	public int price;
	public String switch_type;
	public Orders m_Orders;
	public Storage m_Storage;

	public Mechanicalkeyboard(){

	}

	~Mechanicalkeyboard(){

	}

	/* Begin - EA generated code for Parts and Ports */

	public string Port1 ;

	/* End - EA generated code for Parts and Ports */

}//end Mechanicalkeyboard