///////////////////////////////////////////////////////////
//  Orders.cs
//  Implementation of the Class Orders
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:41:02
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Orders : Entity {

	public int cost;
	public int count;
	public int id;
	public bool isDelivered;
	public List<Keyboard> mechanicalkeyboards;
	public String status;
	public Users user;

	public Orders(){

	}

	~Orders(){

	}

}//end Orders