///////////////////////////////////////////////////////////
//  PaymentSystemController.cs
//  Implementation of the Class PaymentSystemController
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:40:53
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class PaymentSystemController : AbstractBaseController {

	public UserController m_UserController;
	public DirectorController m_DirectorController;

	public PaymentSystemController(){

	}

	~PaymentSystemController(){

	}

	private void performTransaction(){

	}

	public HttpResponse processRequest(){

		return null;
	}

}//end PaymentSystemController