///////////////////////////////////////////////////////////
//  PrinterController.cs
//  Implementation of the Class PrinterController
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:40:12
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class PrinterController : AbstractBaseController {

	public PrinterController(){

	}

	~PrinterController(){

	}

	private void printReport(){

	}

	public override HttpResponse processRequest(){

		return null;
	}

}//end PrinterController