///////////////////////////////////////////////////////////
//  ProviderController.cs
//  Implementation of the Class ProviderController
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:39:44
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ProviderController : AbstractBaseController {

	public ProviderController(){

	}

	~ProviderController(){

	}

	private void addMechanicalkeyboards(){

	}

	public override HttpResponse processRequest(){

		return null;
	}

}//end ProviderController