///////////////////////////////////////////////////////////
//  Report.cs
//  Implementation of the Class Report
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:40:44
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Report {

	public int id;
	public String reportText;

	public Report(){

	}

	~Report(){

	}

}//end Report