///////////////////////////////////////////////////////////
//  Roles.cs
//  Implementation of the Class Roles
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:41:32
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Roles : Entity {

	public int id;
	public String name;

	public Roles(){

	}

	~Roles(){

	}

}//end Roles