///////////////////////////////////////////////////////////
//  Storage.cs
//  Implementation of the Class Storage
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:41:20
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Storage : Entity {

	public int amount;
	public int id;
	public bool inCatalog;
	public List<Keyboard> mechanicalkeyboards;
	public ManagerController m_ManagerController;

	public Storage(){

	}

	~Storage(){

	}

}//end Storage