///////////////////////////////////////////////////////////
//  Users.cs
//  Implementation of the Class Users
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:41:27
//  Original author: Алексей
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Users : Entity {

	public String email;
	public int id;
	public String login;
	public int mechanicalkeyboards;
	public String name;
	public String passwordHash;
	public Roles role;
	public Roles m_Roles;
	public Orders m_Orders;

	public Users(){

	}

	~Users(){

	}

}//end Users