///////////////////////////////////////////////////////////
//  UserController.cs
//  Implementation of the Class UserController
//  Generated by Enterprise Architect
//  Created on:      12-дек.-2020 18:40:04
//  Original author: user
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class UserController : AbstractBaseController {

	private PaymentSystemController paymentSystemController;

	public UserController(){

	}

	~UserController(){

	}

	/// 
	/// <param name="keyboard"></param>
	private void addToCart(Mechanicalkeyboard keyboard){

	}

	private void checkout(){

	}

	/// 
	/// <param name="keyboard"></param>
	private void deleteFromCart(Mechanicalkeyboard keyboard){

	}

	/// 
	/// <param name="keyboard"></param>
	private void editCart(Mechanicalkeyboard keyboard){

	}

	/// 
	/// <param name="filter"></param>
	private List<Keyboard> findFilteredKeyboards(String filter){

		return null;
	}

	private List<Keyboard> getCartList(){

		return null;
	}

	private Mechanicalkeyboard getCharacteristics(){

		return null;
	}

	private List<Keyboard> getOrders(){

		return null;
	}

	private void logout(){

	}

	public override HttpResponse processRequest(){

		return null;
	}

}//end UserController